version: '3.4'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zk1
    container_name: zk1
    ports:
      - 2181:2181
    volumes:
      - "~/zk_kafka/zk/zoo1/data:/data"
      - "~/zk_kafka/zk/zoo1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 
    networks:
      zk_kafka:
        ipv4_address: 172.19.0.11

  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
    volumes:
    - ~/zk_kafka/kafka/kafka1/logs:/kafka
    external_links:
    - zk1
    networks:
      zk_kafka:
        ipv4_address: 172.19.0.14

networks:
  zk_kafka:
    external:
      name: zk_kafka